### ISSUE TITLE
Add Kafka Connect support

### ISSUE THREAD

**Issue by gunnarmorling** [EnMasseProject/barnabas#11]
In order to use [Debezium](http://debezium.io/) on OpenShift via Barnabas, support for [Kafka Connect](https://docs.confluent.io/current/connect/index.html) will be needed. Debezium comes in form of a set of KC source connectors, so we'd need a way to add one or more of the Debezium connectors to the Connect image.

**Comment by scholzj** [comment]
We have now basic support for [Kafka Connect](https://github.com/EnMasseProject/barnabas#kafka-connect) as well as the [S2I build support](https://github.com/EnMasseProject/barnabas#using-openshift-build-and-s2i-image). I think this issue is now fixed and can be closed.

@gunnarmorling Feel free to reopen it if you think something is still missing or not working.
