### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by tombentley** [EnMasseProject/barnabas#23]
Currently CI builds for PRs seem to consistently fail. The last one failed with:

```
Removing intermediate container 9633bde4df15
Successfully built c1369e1e90d5
Error: Cannot perform an interactive login from a non TTY device
make[1]: *** [all] Error 1
make[1]: Leaving directory `/home/travis/build/EnMasseProject/barnabas/kafka-base'
make: *** [kafka-base] Error 2
The command "make" exited with 2.
```

**Comment by scholzj** [comment]
IMO the problem is that the PRs do not have the credentials for Docker available. This is intentional, since I could open PR which prints the credentials and hijack the account. However even in PRs the travis script runs make and tries to push to Docker Hub. We should probably modify the make files to:
* Build images (and run tests in the future) for PRs and direct commits
