### ISSUE TITLE
Single-file deployments

### ISSUE THREAD

**Issue by tombentley** [EnMasseProject/barnabas#35]
Currently we have a file-per-entity for the zookeeper and kafka deployments. This makes instructions and examples (for example in the `README.md`) more verbose as we have to list and use multiple files. We could merge the entities into a single YAML file to alleviate this.

**Comment by scholzj** [comment]
I think we have two options:
1) Merge all into single file
2) Place them into separate subdirectory (e.g. `resources/kubernetes`) and the whole directory can be created with one command. This will allow us to keep separate files.

**Comment by ppatierno** [comment]
I'm for option 2. I like the idea to have different files for resources. But it's just my opinion ...

**Comment by tombentley** [comment]
One advantage of a single file is that it makes sense if the resources are meant to be deployed together. i.e. if it's useless to have the statefulset without the services then why give people to possibility to deploy one without the other?

That said, I could live with option 2 if that's what you both prefer.

**Comment by ppatierno** [comment]
@scholzj is there something that could make sense having under `openshift` or `kubernetes` directories but that isn't a resource itself (i.e. YAML file) ? If not I'm ok on removing `resources` directory.

**Comment by scholzj** [comment]
@ppatierno Well, looking into it ... we have the cluster-volumes.yaml ... I guess these in theory belong to both Kubernetes and OpenShift. We also still have the hostPath provisioner which also affects both AFAIK. So we probably cannot remove the resources directory

**Comment by tombentley** [comment]
But if `openshift_template.yaml` lives in resources I can't simply say `kubectl create -f path/to/resources`, without getting an ugly error (I assume `kubectl` would carry on creating the rest of the resources, so it wouldn't be the end of the world, but it's not pretty).

**Comment by scholzj** [comment]
@tombentley No, you will `kubectl create -f path/to/resources/kubernetes`

**Comment by ppatierno** [comment]
@scholzj providing a directory to the `create` command, what's the order `kubectl` processes the YAML files ? could it be a problem ?

**Comment by scholzj** [comment]
@ppatierno Good question. But I think it should work fine regardless of the order.

**Comment by ppatierno** [comment]
@scholzj but what happens if the `cluster-volumes.yaml` is processed as tha last file ? it should be the first one. Maybe just some pods restarting due to no volumes for providing storage ?

**Comment by scholzj** [comment]
@ppatierno As I said before - I see the `cluster-volumes.yaml` as something what should stay in `resources` since it is kind of optional and should not be needed in most cases. Would you see that in the `kubernetes` folder?

But even if we include it into the kubernetes directory it will work fine. The Pods who need the storage will wait until they have assigned PV. You can try that already now. My Minikube or even my AWS cluster actually do this already today because they need some time to provision the PVs.

I think where you can have problems is for example if you would deploy the Zookeeper services singificantly later after the statefulsets. In such case you would have problems connecting from Kafka to Zookeeper (regular service) or linking up the Zookeepr cluster (headless service). But I don't think this will be issue if you load them from the dir because they will be loaded almost all together.

I think that the workaround for setting the order is to rename the files ... e.g. `01-zookeeper-service.yaml`, `02-zookeeper-headless-service.yaml`, ...

**Comment by ppatierno** [comment]
@scholzj sorry you mentioned that :-(

Btw because using a single YAML file, the resources are applied/created in the order they appear in the file itself, I think we should enforce something like that even having separate files. The workaround could be the naming ... but it doesn't convince me too much. What if we need to add a resource that should be deployed "in the middle" ? With a single file we just need to put in the right position in the file. With multiple file and using the "XX" prefix, we need to rename all the other files.

Maybe we could have a mixed solution ? Two "big" files with Zookeeper related resources on one side and Kafka on the other side ? Or thinking about the single file ... :-)

I'm a little bit confused now on the best approach.

**Comment by scholzj** [comment]
@ppatierno I can live with single file. And @tombentley actually prefered it AFAIK. So we can go for it. 

This is not a change which someone will be working on for days ... we can probably change our decision faster than what we invested into this discussion :-D.

**Comment by ppatierno** [comment]
@scholzj go ahead !
