### ISSUE TITLE
Better health check for zookeeper

### ISSUE THREAD

**Issue by tombentley** [EnMasseProject/barnabas#59]
We're currently using `echo ruok | nc 127.0.0.1 2181`, but the [documentation](https://zookeeper.apache.org/doc/trunk/zookeeperAdmin.html#The+Four+Letter+Words) says this will return `imok` whether the zookeeper instance is in the quorum or not. We could do better with something like `echo stat  | nc 127.0.0.1 2181 | grep -qE 'Mode: (follower|leader)'`

**Comment by scholzj** [comment]
I don't think I agree with this. The purpose of the healthcheck is not to validate the health of the whole Zookeeper cluster but only of the particular node. Mixing this with the cluster healthcheck would be wrong because it would send even the healthy Pods into restart loop just because the quorum is not achieved. As a result the cluster might have problem to start or recover from some issues.

I agree we will need also some more advanced monitoring to monitor the health of the whole Zookeeper (as well as Kafka) cluster. But I don't whink it should be mixed with the Pod healthcheck.

**Comment by tombentley** [comment]
You're right: this health check would depend on the other pods in the cluster which isn't really the right thing for a per-pod health check.
