### ISSUE TITLE
Kafka template should support configuration of replication factor params

### ISSUE THREAD

**Issue by jpechane** [EnMasseProject/barnabas#64]
As it is possible to configure number of replicas for Kafka it would be also useful to configure default replication factors for
```
offsets.topic.replication.factor
transaction.state.log.replication.factor
config.storage.replication.factor
offset.storage.replication.factor
status.storage.replication.factor

default.replication.factor
```
The default value for the first 5 is 3, for the last one is 1. So I propose to provide two parameters - one for the system topics and one for the default. The reason is that if you dpeloy cluster with less than 3 brokers (typically one for dev environment) it is by definition non-functional as the settings require at leas 3 replicas.

**Comment by scholzj** [comment]
@jpechane I'm a bit confused since my understanding is that some of these options are in Kafka:
* `offsets.topic.replication.factor`
* `transaction.state.log.replication.factor`
* `default.replication.factor`

And some are in Kafka Connect:
* `config.storage.replication.factor`
* `offset.storage.replication.factor`
* `status.storage.replication.factor`

Otherwise the requirement is valid. I had run into this kind of problem my self. So what different configuration parameters would you need? What about this? 
* 1 parameter for Kafka Connect to configure all three factors
* 1 parameter for Kafka to set the `default.replication.factor`
* 1 parameter for Kafka to set `offsets.topic.replication.factor` and `transaction.state.log.replication.factor`

That should probably cover it for you, right?

**Comment by jpechane** [comment]
I am sorry for the confusion. Yes, you are right I've mixed both Kafka and Connect together. I agree with your propal as it makes sens to group the options as described.

**Comment by scholzj** [comment]
After some further discussion in the PR, we decided to use separate parameter for each Kafka / Kafka Connect option.
